<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <AssemblyName>HondaTuner</AssemblyName>
    <RootNamespace>HondaTuner</RootNamespace>
    <ApplicationIcon></ApplicationIcon>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="honda_b16_engine.obj">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
